WIP - fix pitch black
freenet/fred pull request #722
Opened 2021-01-23 22:59 UTC by ArneBab

This is initial work for fixing the pitch black attack. It is as of yet untested and hacked in at the place that seemed to fit, but not yet discussed enough.

2021-02-05 19:27 UTC, desyncr commented
@ArneBab What does it mean that this is the first part? Simulation will be a second PR or will be added to this one? Or it's that there are other missing parts the will need to be added later on?

2021-02-06 21:06 UTC, ArneBab commented
desyncr <notifications@github.com> writes:

> @ArneBab What does it mean that this is the first part? Simulation
> will be a second PR or will be added to this one? Or it's that there
> are other missing parts the will need to be added later on?

It means that this still needs simulation, and it needs to be merged.

Best wishes,
Arne
-- 
Unpolitisch sein
heißt politisch sein
ohne es zu merken

2021-03-05 09:04 UTC, nextgens requested changes

2021-03-05 09:52 UTC, nextgens commented
Why do we insert/check both a KSK and a CHK? Wouldn't just a KSK be enough?

2021-03-06 17:37 UTC, ArneBab commented
We insert both KSK and CHK, because an attacker might decide to put its own nodes into the cleared positions to prevent detection, but simply fake CHK store actions. This would effectively kill large files in Freenet while not being visible when checking only SSKs (=KSK).

2021-03-13 12:42 UTC, ArneBab commented on src/freenet/node/LocationManager.java
> +                        .format(LocalDateTime.now().minus(Duration.ofDays(1)));
good point — fixed. Thank you!

2021-03-13 12:42 UTC, ArneBab commented on src/freenet/node/LocationManager.java
> +                            f.delete();
I’m now checking for the boolean and using deleteOnExit if deletion failed.

2021-03-13 12:43 UTC, ArneBab commented on src/freenet/node/LocationManager.java
> +                            && !name.contains(isoDateStringToday));
I now list once and then stream+filter for the specifics.

2021-03-13 12:51 UTC, ArneBab commented on src/freenet/node/LocationManager.java
> +            expectedContent = Base64.decode(
I now write bytes directly. I had that for easier debugging, but there is no use left now.

2021-03-13 12:52 UTC, ArneBab commented on src/freenet/node/LocationManager.java
> +            try (BufferedWriter bufferedWriter = new BufferedWriter(new OutputStreamWriter(
I now only have the FileOutputStream in the try block, because bytes are simpler :-)

2021-03-13 12:52 UTC, ArneBab commented on src/freenet/node/LocationManager.java
> +            case TOO_BIG:
even easier: just replaced with DNF check.

2021-03-13 12:53 UTC, ArneBab commented on src/freenet/node/LocationManager.java
> +            case ROUTE_NOT_FOUND:
I’m now following that route: just check for DNF. Thank you!

2021-03-13 18:11 UTC, merged